---
- name: Create a new mysql database
  hosts: all
  become: yes
  tasks:
   - name: Set MySQL root Password
     mysql_user:
        login_user: 'root'
        login_password: ''
        name: 'root'
        password: '{{ mysql_root_pass }}'
        state: present
   - name: Create a user
     mysql_user:
        name: wiki
        password: '{{ wiki_pass }}'
        state: present
   - name: Create a new mysql database with name wikidatabase
     mysql_db:
      name: wikidatabase
      state: present
      login_user: "root"
      login_password: '{{ mysql_root_pass }}'
   - name: Grant privileges to newly created DB
     mysql_user:
      login_user: "root"
      login_password: '{{ mysql_root_pass }}'
      priv:
        'wikidatabase.*': 'ALL,GRANT'
